const companyKeys = {
  COMPANY: 'COMPANY',
  CRYPTOCLIENT: 'CRYPTOCLIENT',
  GLN: 'GLN',
  GS1_AI: 'GS1-AI',
  MAH_SALER: 'MAH-SALER',
  MD_CHANGE_STATE: 'MD-CHANGE-STATE',
  ME: 'ME',
  MEEEEE: 'MEEEEE',
  SHIPMENT_ORDER: 'SHIPMENT-ORDER',
  SiteLocationMD: 'SiteLocationMD',
  SiteLocationPO: 'SiteLocationPO',
  SNCLIENT: 'SNCLIENT',
  TL_CARRIER: 'TL-CARRIER',
  TL_COUNTRY: 'TL-COUNTRY',
  TL_COUNTRYCODE: 'TL-COUNTRYCODE',
  TL_COUNTRYCODECODE: 'TL-COUNTRYCODECODE',
  TRACE_TAG: 'TRACE-TAG',
};

export default companyKeys;


// CRYPTOCLIENT: 'CRYPTOCLIENT',
// MD_CHANGE_STATE: 'MD-CHANGE-STATE',
// ME: 'ME',
// MEEEEE: 'MEEEEE',
// SiteLocationMD: 'SiteLocationMD',
// SiteLocationPO: 'SiteLocationPO',
// TL_COUNTRY: 'TL-COUNTRY',
// TL_COUNTRYCODECODE: 'TL-COUNTRYCODECODE',
