export const Styles = (width, height) => ({
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: height,
  },
  titles: index => ({
    backgroundColor: index % 2 === 0 ? '#FFFFFF' : '#C8C8C8',
    borderWidth: 1,
    borderStyle: 'solid',
    height: 40,
    fontSize: 16,
    fontWeight: '600',
    minWidth: 100,
    justifyContent: 'center',
    alignItems: 'center',
    display: 'flex',
  }),
  permDiv: {
    display: 'flex',
  },
  columnsArray: (index = 0) => ({
    backgroundColor: index % 2 === 0 ? '#FFFFFF' : '#C8C8C8',
    width: 70,
    height: 40,
    textAlign: 'center',
    borderWidth: 1,
    borderStyle: 'solid',
  }),
  header: {
    display: 'flex',
    flexDirection: 'row',
    height: height * 0.1,
    alignItems: 'center',
  },
  addText: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: width * 0.1,
    height: 40,
    fontSize: 14,
    fontWeight: '600',
    borderWidth: 0,
    borderRadius: 5,
    backgroundColor: '#C8C8C8',
    color: 'black',
    marginLeft: 10,
    marginRight: 20,
    marginTop: 10,
    marginBottom: 10,
  },
  editIcon: {
    width: 35,
    height: 35,
    color: 'red',
  },
  searchInput: {
    width: width * 0.3,
    height: 40,
    backgroundColor: 'white',
    fontSize: 16,
    color: 'black',
    textAlign: 'center',
    borderRadius: 5,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#C8C8C8',
  },
  searchIcon: {
    width: 30,
    height: 30,
  },
  searchBtnContainer: {
    width: width * 0.05,
    height: 40,
    marginLeft: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 5,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#C8C8C8',
  },
  mainDiv: {
    display: 'flex',
  },
});
